# Generated by Django 5.0.2 on 2024-06-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='bills', to='core.profile'),
        ),
    ]
