# Generated by Django 5.0.2 on 2024-06-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0005_alter_payment_bill"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
