# Generated by Django 5.0.2 on 2024-06-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0006_payment_is_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="sum",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
